import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import test from "node:test";
import {
  aiBuilderVaultQueries,
} from "../.test-dist/ai-builder.js";
import {
  expandDateFormat,
  expandDateTemplate,
} from "../.test-dist/dates.js";

test("AI Builder extracts focused vault search terms from reference prompts", () => {
  assert.deepEqual(
    aiBuilderVaultQueries("Build a table with links to all the pages that reference opensips in this vault"),
    ["opensips"],
  );
  assert.deepEqual(aiBuilderVaultQueries("Summarize all pages pertaining to opensips."), [
    "opensips",
  ]);
});

test("quick command palette exposes initial editor commands", () => {
  const app = readFileSync("src/App.tsx", "utf8");
  const commandPalette = readFileSync("src/command-palette/commands.ts", "utf8");
  const editorCommands = readFileSync("src/editor/commands.ts", "utf8");
  const editorPane = readFileSync("src/editor/EditorPane.tsx", "utf8");
  const editorOptions = readFileSync("src/editor/editor-options.ts", "utf8");
  const vaultPersistence = readFileSync("src/vault/persistence.ts", "utf8");
  const css = readFileSync("src/App.css", "utf8");
  const backend = readFileSync("src-tauri/src/lib.rs", "utf8");
  const vaultBackend = readFileSync("src-tauri/src/vault.rs", "utf8");

  assert.match(commandPalette, /type CommandPaletteCommand/);
  assert.match(commandPalette, /type CommandPaletteScope = "root" \| "ai" \| "insert" \| "format" \| "table"/);
  assert.match(app, /commandPaletteCommands/);
  assert.match(app, /insertCommandPaletteCommands/);
  assert.match(app, /canvasInsertCommandPaletteCommands/);
  assert.match(app, /canvasCommandPaletteCommands/);
  assert.match(app, /editorCommandPaletteCommands/);
  assert.match(app, /function hasActiveDocumentTab\(\)/);
  assert.match(app, /Open or create a note before using the command palette/);
  assert.match(app, /activeDocumentTab[\s\S]*activeDocumentIsCanvas[\s\S]*activeDocumentIsMarkdown[\s\S]*canvasCommandPaletteCommands[\s\S]*editorCommandPaletteCommands[\s\S]*\[\]/);
  assert.match(app, /activeDocumentIsCanvas\s*\?\s*canvasInsertCommandPaletteCommands\s*:\s*activeDocumentIsMarkdown\s*\?\s*insertCommandPaletteCommands\s*:\s*\[\]/);
  assert.match(app, /activeCommandPaletteCommands/);
  assert.match(app, /setCanvasCommandRequest/);
  assert.match(editorPane, /commandRequest=\{isActiveGroup \? canvasCommandRequest : null\}/);
  assert.match(app, /id: "create-tidbit"/);
  assert.match(app, /title: "Create Tidbit"/);
  assert.match(app, /expandDateTemplate\(tidbitSettings\.pathPattern\)/);
  assert.match(vaultPersistence, /"create_vault_markdown_file"/);
  assert.match(app, /id: "insert-rich-link"/);
  assert.match(app, /title: "Insert rich link"/);
  assert.match(app, /id: "insert-columns"/);
  assert.match(app, /title: "Insert columns"/);
  assert.match(app, /id: "gallery-layout"/);
  assert.match(app, /title: "Gallery layout"/);
  assert.match(app, /id: "insert-callout"/);
  assert.match(app, /title: "Insert callout"/);
  assert.match(app, /id: "insert-collapse"/);
  assert.match(app, /title: "Insert collapse"/);
  assert.match(app, /id: "insert-html-block"/);
  assert.match(app, /title: "Insert HTML block"/);
  assert.match(app, /id: "insert-mermaid-diagram"/);
  assert.match(app, /title: "Insert Mermaid diagram"/);
  assert.match(app, /function insertMermaidDiagram\(\)/);
  assert.match(app, /flowchart TD\\n  A\[Start\] --> B\[Done\]/);
  assert.match(app, /id: "insert-table-of-contents"/);
  assert.match(app, /title: "Insert table of contents"/);
  assert.match(app, /id: "insert-menu"/);
  assert.match(app, /title: "Insert \.\.\."/);
  assert.match(app, /function formatSelectionAsKeyboardKey\(\)/);
  const markdownExtensions = readFileSync("src/editor/markdown-extensions.tsx", "utf8");

  assert.match(markdownExtensions, /function createDelimitedMarkdownMarkExtension/);
  assert.match(markdownExtensions, /function findSingleTildeDelimiter/);
  assert.match(editorOptions, /name: "highlight"/);
  assert.match(editorOptions, /delimiter: "=="/);
  assert.match(editorOptions, /tag: "mark"/);
  assert.match(editorOptions, /name: "superscript"/);
  assert.match(editorOptions, /delimiter: "\^"/);
  assert.match(editorOptions, /tag: "sup"/);
  assert.match(editorOptions, /name: "subscript"/);
  assert.match(editorOptions, /delimiter: "~"/);
  assert.match(editorOptions, /tag: "sub"/);
  assert.match(editorCommands, /function formatSelectionWithMark/);
  assert.match(editorCommands, /marks: \[\{ type: markType \}\]/);
  assert.match(app, /id: "format-strikethrough"/);
  assert.match(app, /title: "Strikethrough"/);
  assert.match(app, /formatSelectionWithMark\(editor, "strike", "strikethrough", setStatus\)/);
  assert.match(app, /id: "format-highlight"/);
  assert.match(app, /title: "Highlight"/);
  assert.match(app, /formatSelectionWithMark\(editor, "highlight", "a highlight", setStatus\)/);
  assert.match(app, /id: "format-superscript"/);
  assert.match(app, /title: "Superscript"/);
  assert.match(app, /formatSelectionWithMark\(editor, "superscript", "superscript", setStatus\)/);
  assert.match(app, /id: "format-subscript"/);
  assert.match(app, /title: "Subscript"/);
  assert.match(app, /formatSelectionWithMark\(editor, "subscript", "subscript", setStatus\)/);
  assert.match(app, /id: "format-keyboard"/);
  assert.match(app, /title: "Keyboard"/);
  assert.match(app, /formatSelectionWithMark\(editor, "keyboardKey", "a keyboard key", setStatus\)/);
  assert.match(app, /Wrap selected text in <kbd> tags/);
  assert.match(css, /\.editor-surface mark/);
  assert.match(css, /\.editor-surface sup,/);
  assert.match(css, /\.editor-surface sub/);
  assert.match(app, /id: "format-menu"/);
  assert.match(app, /title: "Format \.\.\."/);
  assert.match(app, /id: "canvas-add-card"/);
  assert.match(app, /title: "Add Card"/);
  assert.match(app, /id: "canvas-add-note-from-vault"/);
  assert.match(app, /title: "Add Note From Vault"/);
  assert.match(app, /id: "canvas-add-media-from-vault"/);
  assert.match(app, /title: "Add Media From Vault"/);
  assert.match(app, /id: "canvas-add-web-page"/);
  assert.match(app, /title: "Add Web Page"/);
  assert.match(app, /id: "canvas-create-group"/);
  assert.match(app, /title: "Create Group"/);
  assert.match(app, /setCommandPaletteScope\("insert"\)/);
  assert.match(commandPalette, /Insert commands/);
  assert.match(commandPalette, /Canvas insert commands/);
  assert.match(commandPalette, /Type an insert command/);
  assert.match(commandPalette, /Type a canvas insert command/);
  assert.match(app, /setCommandPaletteScope\("format"\)/);
  assert.match(commandPalette, /Format commands/);
  assert.match(commandPalette, /Type a format command/);
  assert.match(app, /function appendTableOfContentsBlock\(\)/);
  assert.match(app, /insertContent\("```toc\\n```", \{ contentType: "markdown" \}\)/);
  assert.match(app, /role="combobox"/);
  assert.match(app, /role="listbox"/);
  assert.match(app, /runCommandPaletteCommand/);
  assert.match(app, /handleCommandPaletteKeyDown/);
  assert.match(app, /setCommandPaletteScope\("root"\)/);
  assert.match(app, /event\.key === "Escape"[\s\S]*commandPaletteScope !== "root"[\s\S]*setCommandPaletteScope\("root"\)[\s\S]*closeCommandPalette\(\)/);
  assert.match(app, /commandPaletteResultsRef/);
  assert.match(app, /filteredCommandPaletteCommands\.length - 1/);
  assert.match(app, /scrollIntoView\(\{ block: "nearest" \}\)/);
  assert.match(app, /moveSelectableIndex\(index, filteredCommandPaletteCommands\.length, 1\)/);
  assert.match(app, /moveSelectableIndex\(index, filteredCommandPaletteCommands\.length, -1\)/);
  assert.match(css, /\.command-palette-screen/);
  assert.match(css, /\.command-palette-card/);
  assert.match(css, /\.command-palette-scopebar/);
  assert.match(css, /\.command-palette-results/);
  assert.match(vaultBackend, /pub\(crate\) fn create_vault_markdown_file/);
  assert.match(backend, /create_vault_markdown_file,/);
});

test("AI commands use vault settings and review output before editing", () => {
  const app = readFileSync("src/App.tsx", "utf8");
  // AI execution logic lives in the hook; palette wiring stays in App.
  const aiImplementation = app + "\n" + readFileSync("src/ai/use-ai-commands.ts", "utf8");
  const settingsDialog = readFileSync("src/settings/SettingsDialog.tsx", "utf8");
  const vaultPersistence = readFileSync("src/vault/persistence.ts", "utf8");
  const commandPalette = readFileSync("src/command-palette/commands.ts", "utf8");
  const editorCommands = readFileSync("src/editor/commands.ts", "utf8");
  const appTypes = readFileSync("src/lib/app-types.ts", "utf8");
  const aiBuilderModule = readFileSync("src/lib/ai-builder.ts", "utf8");
  const settings = readFileSync("src/lib/settings.ts", "utf8");
  const defaults = readFileSync("src/lib/defaults.ts", "utf8");
  const settingsState = readFileSync("src/settings/useSettingsState.ts", "utf8");
  const css = readFileSync("src/App.css", "utf8");
  const backend = readFileSync("src-tauri/src/lib.rs", "utf8");
  const aiBackend = readFileSync("src-tauri/src/ai.rs", "utf8");
  const aiHistoryBackend = readFileSync("src-tauri/src/ai_history.rs", "utf8");
  const modelsBackend = readFileSync("src-tauri/src/models.rs", "utf8");

  assert.match(appTypes, /export type AiSettings/);
  assert.match(appTypes, /export type AiBuilderHistoryStore/);
  assert.match(appTypes, /export type AiBuilderHistoryTurn/);
  assert.match(appTypes, /superseded\?: boolean/);
  assert.match(appTypes, /replacedByTurnId\?: string \| null/);
  assert.match(appTypes, /export type AiPageBuilderAssetRequest/);
  assert.match(appTypes, /export type AiPageBuilderResponse/);
  assert.match(appTypes, /export type AiModelListResponse/);
  assert.match(appTypes, /export type AiConnectionTestResponse/);
  assert.match(appTypes, /ai\?: AiSettings \| null/);
  assert.match(defaults, /defaultAiBaseUrl = "https:\/\/api\.openai\.com\/v1"/);
  assert.match(defaults, /defaultAiModel = "gpt-5\.5"/);
  assert.match(settings, /defaultAiSettings: AiSettings/);
  assert.match(settings, /function normalizeAiSettings/);
  assert.match(settings, /function sameAiSettings/);
  assert.match(settingsDialog, /settingsTab === "ai"/);
  assert.match(settingsDialog, /Enable AI commands/);
  assert.match(settingsDialog, /OpenAI-compatible backend/);
  assert.match(settingsDialog, /type="password"/);
  const aiSettingsStart = settingsDialog.indexOf('aria-label="AI settings"');
  const aiSettingsEnd = settingsDialog.indexOf('settingsTab === "debug"', aiSettingsStart);
  const aiSettingsPanel = settingsDialog.slice(aiSettingsStart, aiSettingsEnd);

  assert.ok(aiSettingsStart > -1);
  assert.ok(aiSettingsEnd > aiSettingsStart);
  assert.doesNotMatch(aiSettingsPanel, /enabled: event\.currentTarget\.checked/);
  assert.doesNotMatch(aiSettingsPanel, /baseUrl: event\.currentTarget\.value/);
  assert.doesNotMatch(aiSettingsPanel, /model: event\.currentTarget\.value/);
  assert.doesNotMatch(aiSettingsPanel, /apiKey: event\.currentTarget\.value/);
  assert.match(aiImplementation, /function aiModelOptions/);
  assert.match(aiImplementation, /async function refreshAiModels/);
  assert.match(aiImplementation, /invoke<AiModelListResponse>\("list_ai_models"/);
  assert.match(aiImplementation, /async function testAiConnection/);
  assert.match(aiImplementation, /invoke<AiConnectionTestResponse>\("test_ai_connection"/);
  assert.match(settingsState, /const \[aiTestStatus, setAiTestStatus\]/);
  assert.match(aiImplementation, /const \[aiSubmitting, setAiSubmitting\]/);
  assert.match(aiImplementation, /const \[aiSubmittingTitle, setAiSubmittingTitle\]/);
  assert.match(aiImplementation, /const \[aiPageBuilderOpen, setAiPageBuilderOpen\]/);
  assert.match(aiImplementation, /const \[aiPageBuilderPrompt, setAiPageBuilderPrompt\]/);
  assert.match(aiImplementation, /const \[aiPageBuilderAssetReview, setAiPageBuilderAssetReview\]/);
  assert.match(aiImplementation, /const \[aiPageBuilderImportingAssets, setAiPageBuilderImportingAssets\]/);
  assert.match(aiImplementation, /const \[aiBuilderHistory, setAiBuilderHistory\]/);
  assert.match(aiImplementation, /setAiTestStatus\("success"\)/);
  assert.match(aiImplementation, /setAiTestStatus\("error"\)/);
  assert.match(settingsDialog, /className=\{`ai-test-indicator/);
  assert.match(settingsDialog, /AI API test passed/);
  assert.match(settingsDialog, /AI API test failed/);
  assert.match(settingsDialog, /Refresh Models/);
  assert.match(settingsDialog, /Test API/);
  assert.match(settingsDialog, /<select[\s\S]*value=\{aiDraft\.model\}/);
  assert.doesNotMatch(aiImplementation, /id: "ai-reword-selection"/);
  assert.doesNotMatch(aiImplementation, /AI: Reword selection/);
  assert.match(aiImplementation, /id: "ai-page-builder"/);
  assert.match(aiImplementation, /AI: Page Builder/);
  assert.match(aiImplementation, /id: "ai-improve-writing-selection"/);
  assert.match(aiImplementation, /AI: Improve writing/);
  assert.match(aiImplementation, /id: "ai-fix-spelling-grammar-selection"/);
  assert.match(aiImplementation, /id: "ai-shorten-selection"/);
  assert.match(aiImplementation, /id: "ai-expand-selection"/);
  assert.match(aiImplementation, /id: "ai-tone-formal-selection"/);
  assert.match(aiImplementation, /id: "ai-tone-casual-selection"/);
  assert.match(aiImplementation, /id: "ai-tone-direct-selection"/);
  assert.match(aiImplementation, /id: "ai-tone-polished-selection"/);
  assert.match(aiImplementation, /id: "ai-summarize-selection"/);
  assert.match(aiImplementation, /id: "ai-extract-tasks-selection"/);
  assert.match(aiImplementation, /id: "ai-create-outline-selection"/);
  // The diagram command emits an editable mermaid block below the source
  // text (never replacing it) and works on the selection or the whole note.
  assert.match(aiImplementation, /id: "ai-diagram-selection"/);
  assert.match(
    app,
    /id: "ai-diagram-selection",[\s\S]{0,900}?runAiSelectionOrDocumentCommand\([\s\S]{0,900}?"insert-below-selection",/,
  );
  assert.match(aiImplementation, /Return only one fenced ```mermaid code block/);
  assert.match(aiImplementation, /id: "ai-generate-title"/);
  assert.match(aiImplementation, /id: "ai-continue-writing"/);
  assert.match(aiImplementation, /id: "ai-explain-selection"/);
  assert.match(aiImplementation, /const aiCommandPaletteCommands: CommandPaletteCommand\[\] = savedAiSettings\(\)\.enabled/);
  assert.match(aiImplementation, /id: "ai-menu"/);
  assert.match(aiImplementation, /title: "AI \.\.\."/);
  assert.match(aiImplementation, /setCommandPaletteScope\("ai"\)/);
  assert.match(aiImplementation, /commandPaletteScope === "ai"[\s\S]*aiCommandPaletteCommands[\s\S]*commandPaletteScope === "insert"[\s\S]*activeInsertCommandPaletteCommands[\s\S]*commandPaletteScope === "format"[\s\S]*formatCommandPaletteCommands[\s\S]*commandPaletteScope === "table"[\s\S]*tableCommandPaletteCommands[\s\S]*commandPaletteCommands/);
  assert.match(commandPalette, /AI commands/);
  assert.match(commandPalette, /Type an AI command/);
  assert.match(aiImplementation, /Enable AI commands in Settings before using this command/);
  assert.match(aiImplementation, /const settings = savedAiSettings\(\)/);
  assert.match(editorCommands, /function currentCursorContext/);
  assert.match(aiImplementation, /function openAiPageBuilder/);
  assert.match(aiImplementation, /function stripJsonCodeFence/);
  assert.match(aiImplementation, /function parseAiPageBuilderResponse/);
  assert.match(aiImplementation, /function pageBuilderAssetCandidateUrls/);
  assert.match(aiImplementation, /function replaceAiPageBuilderAssetPlaceholders/);
  assert.match(aiImplementation, /maxAiBuilderHistoryTurnsPerFile/);
  assert.match(aiImplementation, /maxAiBuilderPromptHistoryTurns/);
  assert.match(aiBuilderModule, /maxAiBuilderVaultQueries/);
  assert.match(aiBuilderModule, /maxAiBuilderVaultFiles/);
  assert.match(aiBuilderModule, /maxAiBuilderVaultFileChars/);
  assert.match(aiImplementation, /function aiBuilderHistoryContext/);
  assert.match(aiImplementation, /async function loadAiBuilderHistory/);
  assert.match(aiImplementation, /function persistAiBuilderHistory/);
  assert.match(aiImplementation, /function upsertAiBuilderHistoryTurn/);
  assert.match(aiImplementation, /function updateAiBuilderHistoryTurn/);
  assert.match(aiImplementation, /function moveAiBuilderHistoryKey/);
  assert.match(aiImplementation, /function clearActiveAiBuilderHistory/);
  assert.match(aiImplementation, /function wrapAiBuilderMarkdown/);
  assert.match(aiImplementation, /function hasAiBuilderMarkedBlock/);
  assert.match(aiImplementation, /function latestReplaceableAiBuilderTurn/);
  assert.match(aiImplementation, /function replaceAiBuilderMarkedBlock/);
  assert.match(aiImplementation, /glyphary-ai-builder:start/);
  assert.match(aiImplementation, /glyphary-ai-builder:end/);
  assert.match(aiImplementation, /aiBuilderReplaceTurnId/);
  assert.match(aiImplementation, /setAiPageBuilderReplaceTurnId\(latestReplaceableAiBuilderTurn\(\)\?\.id \?\? null\)/);
  assert.match(aiBuilderModule, /AI Builder prompt-context helpers/);
  assert.match(aiBuilderModule, /export function aiBuilderPromptRequestsVaultContext/);
  assert.match(aiBuilderModule, /export function aiBuilderPromptRequestsTaskContext/);
  assert.match(aiBuilderModule, /export function aiBuilderVaultQueries/);
  assert.match(aiBuilderModule, /export function aiBuilderVaultContextText/);
  assert.match(aiBuilderModule, /export function aiBuilderEffectiveTaskQueries/);
  assert.match(aiImplementation, /async function aiBuilderSearchVaultNotes/);
  assert.match(aiImplementation, /async function aiBuilderSearchVaultTasks/);
  assert.match(aiImplementation, /async function aiBuilderVaultContext/);
  assert.match(vaultPersistence, /"search_vault"/);
  assert.match(vaultPersistence, /"read_vault_file"/);
  assert.match(aiImplementation, /function normalizeMalformedVaultImageMarkdown/);
  assert.match(aiImplementation, /function normalizeAiMarkdownForApply/);
  assert.match(aiImplementation, /invalid nested form `!\[Logo\]\(!\[\[logo\.png\]\]\)`/);
  assert.match(aiImplementation, /const vaultImageMarkdown = `!\[\[\$\{saved\.fileName\}\]\]`/);
  assert.match(aiImplementation, /normalizeAiMarkdownForApply\(response\.output\)/);
  assert.match(aiImplementation, /normalizeAiMarkdownForApply\(builderResponse\.markdown\)/);
  assert.match(aiImplementation, /Recent AI Builder conversation for this file/);
  assert.match(aiImplementation, /Replacement target/);
  assert.match(aiImplementation, /Vault retrieval context/);
  assert.match(aiImplementation, /Gathering vault context for AI: Page Builder/);
  assert.match(aiImplementation, /Cite source notes with \[\[Note Name\]\] links/);
  assert.match(aiImplementation, /upsertAiBuilderHistoryTurn\(historyKey, turn\)/);
  assert.match(aiImplementation, /superseded: true/);
  assert.match(aiImplementation, /replacedByTurnId: review\.aiBuilderTurnId/);
  assert.match(aiImplementation, /applied: true/);
  assert.match(aiImplementation, /async function importAiPageBuilderAssets/);
  assert.match(aiImplementation, /function aiPageBuilderContext/);
  assert.match(aiImplementation, /async function runAiPageBuilder/);
  assert.match(aiImplementation, /aiPageBuilderMarkdownContextLimit/);
  assert.match(aiImplementation, /Return only valid JSON with this shape/);
  assert.match(aiImplementation, /\{\{asset:stable-placeholder-id\}\}/);
  assert.match(aiImplementation, /logo\.clearbit\.com/);
  assert.match(aiImplementation, /google\.com\/s2\/favicons/);
  assert.match(aiImplementation, /Glyphary-native Markdown blocks/);
  assert.match(aiImplementation, /::: callout/);
  assert.match(aiImplementation, /::: columns/);
  assert.match(aiImplementation, /Use raw HTML only when Markdown or Glyphary block syntax cannot express/);
  assert.match(aiImplementation, /async function runAiTextCommand/);
  assert.match(aiImplementation, /runAiSelectionCommand/);
  assert.match(aiImplementation, /runAiSelectionOrDocumentCommand/);
  assert.match(aiImplementation, /runAiContinueWritingCommand/);
  assert.match(aiImplementation, /applyMode: "replace-selection" \| "insert-below-selection" \| "insert-at-cursor"/);
  assert.match(aiImplementation, /setAiSubmittingTitle\(title\)/);
  assert.match(aiImplementation, /invoke<AiTransformResponse>\("run_ai_transform"/);
  assert.match(aiImplementation, /className="ai-progress-screen"/);
  assert.match(aiImplementation, /Waiting for AI response/);
  assert.match(aiImplementation, /className="ai-builder-screen"/);
  assert.match(aiImplementation, /className="ai-builder-card"/);
  assert.match(aiImplementation, /className="ai-builder-asset-screen"/);
  assert.match(aiImplementation, /className="ai-builder-asset-card"/);
  assert.match(aiImplementation, /className="ai-builder-asset-list"/);
  assert.match(aiImplementation, /className="ai-builder-history"/);
  assert.match(aiImplementation, /className="ai-builder-history-list"/);
  assert.match(aiImplementation, /Replace Previous/);
  assert.match(aiImplementation, /aiReview\.applyMode === "insert-at-cursor" && !aiReview\.aiBuilderReplaceTurnId/);
  assert.match(aiImplementation, /Replaced/);
  assert.match(aiImplementation, /aria-label="AI Page Builder"/);
  assert.match(aiImplementation, /aria-label="AI Builder history"/);
  assert.match(aiImplementation, /aria-label="Review AI Page Builder assets"/);
  assert.match(aiImplementation, /closeAiPageBuilderOnEscape/);
  assert.match(aiImplementation, /closeAiPageBuilderAssetReviewOnEscape/);
  assert.match(aiImplementation, /invoke<SavedAsset>\("import_remote_vault_image_asset"/);
  assert.match(aiImplementation, /setAiPageBuilderOpen\(false\)/);
  assert.match(aiImplementation, /className="ai-review-screen"/);
  assert.match(aiImplementation, /closeAiReviewOnEscape/);
  assert.match(aiImplementation, /window\.addEventListener\("keydown", closeAiReviewOnEscape\)/);
  assert.match(aiImplementation, /Replace Selection/);
  assert.match(aiImplementation, /Insert Below/);
  assert.match(aiImplementation, /Insert at Cursor/);
  assert.doesNotMatch(aiImplementation, /Insert Result/);
  const aiReviewStart = app.indexOf('className="ai-review-card"');
  const aiReviewEnd = app.indexOf("{aiSubmitting ? (", aiReviewStart);
  const aiReviewDialog = app.slice(aiReviewStart, aiReviewEnd);

  assert.ok(aiReviewStart > -1);
  assert.ok(aiReviewEnd > aiReviewStart);
  assert.doesNotMatch(aiReviewDialog, /className="primary-action"/);
  assert.match(css, /\.ai-builder-card/);
  assert.match(css, /\.ai-builder-history/);
  assert.match(css, /\.ai-builder-history-list/);
  assert.match(css, /\.ai-builder-history-item\.selected/);
  assert.match(css, /\.ai-builder-replace-note/);
  assert.match(css, /\.ai-builder-asset-card/);
  assert.match(css, /\.ai-builder-asset-list/);
  assert.match(css, /\.ai-review-card/);
  assert.match(css, /\.ai-progress-card/);
  assert.match(css, /\.ai-progress-spinner/);
  assert.match(css, /transform-origin: 50% 50%/);
  assert.match(css, /@keyframes glyphary-spin/);
  assert.match(css, /from \{\s*transform: rotate\(0deg\);/);
  assert.match(css, /\.ai-progress-spinner \{\s*animation: glyphary-spin 0\.85s linear infinite !important;/);
  assert.match(css, /\.ai-test-indicator/);
  assert.match(css, /\.ai-test-indicator\.success/);
  assert.match(css, /\.ai-test-indicator\.error/);
  assert.match(modelsBackend, /pub\(crate\) struct AiSettings/);
  assert.match(modelsBackend, /pub\(crate\) struct AiModelListResponse/);
  assert.match(modelsBackend, /pub\(crate\) struct AiConnectionTestResponse/);
  assert.match(modelsBackend, /pub\(crate\) struct AiTransformRequest/);
  assert.match(modelsBackend, /pub\(crate\) struct AiBuilderHistoryStore/);
  assert.match(modelsBackend, /pub\(crate\) struct AiBuilderHistoryTurn/);
  assert.match(modelsBackend, /pub\(crate\) superseded: bool/);
  assert.match(modelsBackend, /pub\(crate\) replaced_by_turn_id: Option<String>/);
  assert.match(aiBackend, /ai_endpoint_url/);
  assert.match(aiBackend, /pub\(crate\) async fn list_ai_models/);
  assert.match(aiBackend, /pub\(crate\) async fn test_ai_connection/);
  assert.match(aiBackend, /requested content/);
  assert.match(aiBackend, /\.get\(ai_endpoint_url\(&settings\.base_url, "models"\)\?\)/);
  assert.match(backend, /import_remote_vault_image_asset,/);
  assert.match(backend, /read_ai_builder_history,/);
  assert.match(backend, /write_ai_builder_history/);
  assert.match(aiHistoryBackend, /AI Builder history persistence/);
  assert.match(aiHistoryBackend, /AI_BUILDER_HISTORY_FILE_NAME/);
  assert.match(aiHistoryBackend, /pub\(crate\) fn read_ai_builder_history/);
  assert.match(aiHistoryBackend, /pub\(crate\) fn write_ai_builder_history/);
  const assetsBackend = readFileSync("src-tauri/src/assets.rs", "utf8");

  assert.match(assetsBackend, /pub\(crate\) async fn import_remote_vault_image_asset/);
  assert.match(assetsBackend, /Remote image URL must use http or https/);
  assert.match(assetsBackend, /CONTENT_TYPE/);
  assert.match(assetsBackend, /content_type\.starts_with\("image\/"\)/);
  const testConnectionStart = aiBackend.indexOf("pub(crate) async fn test_ai_connection");
  const testConnectionEnd = aiBackend.indexOf("#[tauri::command]", testConnectionStart + 1);
  const testConnectionBody = aiBackend.slice(testConnectionStart, testConnectionEnd);

  assert.ok(testConnectionStart > -1);
  assert.ok(testConnectionEnd > testConnectionStart);
  assert.doesNotMatch(testConnectionBody, /max_tokens|max_completion_tokens|temperature/);
  assert.match(aiBackend, /chat\/completions/);
  assert.match(aiBackend, /bearer_auth\(settings\.api_key\)/);
  assert.match(backend, /list_ai_models/);
  assert.match(backend, /test_ai_connection/);
  assert.match(backend, /run_ai_transform/);
});

test("table row and column actions are contextual command palette entries", () => {
  const app = readFileSync("src/App.tsx", "utf8");
  const commandPalette = readFileSync("src/command-palette/commands.ts", "utf8");
  const editorCommands = readFileSync("src/editor/commands.ts", "utf8");
  const editorPane = readFileSync("src/editor/EditorPane.tsx", "utf8");
  const css = readFileSync("src/App.css", "utf8");

  assert.match(app, /const cursorInsideTable/);
  assert.match(app, /editor\.isActive\("table"\)/);
  assert.match(app, /editor\.isActive\("tableCell"\)/);
  assert.match(app, /editor\.isActive\("tableHeader"\)/);
  assert.match(app, /id: "table-add-row-after"/);
  assert.match(app, /title: "Add row after"/);
  assert.match(app, /id: "table-delete-row"/);
  assert.match(app, /title: "Delete row"/);
  assert.match(app, /id: "table-add-column-after"/);
  assert.match(app, /title: "Add column after"/);
  assert.match(app, /id: "table-delete-column"/);
  assert.match(app, /title: "Delete column"/);
  assert.match(app, /id: "table-delete-table"/);
  assert.match(app, /title: "Delete table"/);
  assert.match(app, /id: "table-menu"/);
  assert.match(app, /title: "Table \.\.\."/);
  assert.match(app, /setCommandPaletteScope\("table"\)/);
  assert.match(commandPalette, /Table commands/);
  assert.match(commandPalette, /Type a table command/);
  assert.match(editorCommands, /type TableColumnAlignment = "left" \| "center" \| "right"/);
  assert.match(app, /function handleEditorContextMenu/);
  assert.match(app, /target\?\.closest\("table"\)/);
  assert.match(editorPane, /onContextMenu=\{\(event\) => onEditorContextMenu\(event, groupEditor, groupId\)\}/);
  assert.match(editorCommands, /TableMap\.get\(table\)/);
  assert.match(editorCommands, /map\.cellsInRect/);
  assert.match(editorCommands, /tr\.setNodeMarkup\(tableStart \+ cellPosition/);
  assert.match(editorCommands, /Avoid CellSelection here/);
  assert.match(editorCommands, /Cmd\+Z would restore a visible whole-column selection/);
  assert.match(editorCommands, /const restorePosition = state\.selection\.from/);
  assert.match(editorCommands, /tr\.setSelection\(TextSelection\.create\(tr\.doc, restorePosition\)\)/);
  assert.doesNotMatch(app, /CellSelection\.colSelection/);
  assert.doesNotMatch(app, /setCellAttribute\("align", alignment\)/);
  assert.match(app, /onMouseDown=\{\(event\) => event\.preventDefault\(\)\}/);
  assert.match(app, /Align column\.\.\./);
  assert.match(app, /className="table-context-separator"/);
  assert.match(app, /Left align/);
  assert.match(app, /Center align/);
  assert.match(app, /Right align/);
  assert.match(css, /\.table-context-menu/);
  assert.match(css, /\.table-context-separator/);
  assert.match(css, /\.table-context-submenu-panel/);
  assert.doesNotMatch(app, /\.\.\.tableCommandPaletteCommands/);
  assert.doesNotMatch(app, /label: "\+ Row"/);
  assert.doesNotMatch(app, /label: "- Row"/);
  assert.doesNotMatch(app, /label: "\+ Col"/);
  assert.doesNotMatch(app, /label: "- Col"/);
  assert.doesNotMatch(app, /label: "Drop Table"/);
});
